// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Core.Data;

#nullable disable

namespace Server.Core.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250130181713_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Server.Core.Entities.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ShoeBrandId")
                        .HasColumnType("int");

                    b.Property<int>("ShoeCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ShoeBrandId");

                    b.HasIndex("ShoeCategoryId");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "High-quality Puma shoe, model Air Stride, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma Air Stride",
                            Price = 54.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 37
                        },
                        new
                        {
                            Id = 2,
                            Description = "High-quality Puma shoe, model Ultra Run, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma Ultra Run",
                            Price = 59.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 3,
                            Size = 38
                        },
                        new
                        {
                            Id = 3,
                            Description = "High-quality Reebok shoe, model SpeedFlex, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok SpeedFlex",
                            Price = 64.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 1,
                            Size = 39
                        },
                        new
                        {
                            Id = 4,
                            Description = "High-quality Puma shoe, model PowerStep, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma PowerStep",
                            Price = 69.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 40
                        },
                        new
                        {
                            Id = 5,
                            Description = "High-quality Reebok shoe, model Enduro, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok Enduro",
                            Price = 74.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 3,
                            Size = 41
                        },
                        new
                        {
                            Id = 6,
                            Description = "High-quality Adidas shoe, model CloudFlow, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas CloudFlow",
                            Price = 79.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 1,
                            Size = 42
                        },
                        new
                        {
                            Id = 7,
                            Description = "High-quality Puma shoe, model Solar Glide, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma Solar Glide",
                            Price = 84.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 43
                        },
                        new
                        {
                            Id = 8,
                            Description = "High-quality Adidas shoe, model Velocity Boost, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas Velocity Boost",
                            Price = 89.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 3,
                            Size = 44
                        },
                        new
                        {
                            Id = 9,
                            Description = "High-quality Adidas shoe, model Sprint Edge, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas Sprint Edge",
                            Price = 94.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 1,
                            Size = 45
                        },
                        new
                        {
                            Id = 10,
                            Description = "High-quality Reebok shoe, model TrailBlazer, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok TrailBlazer",
                            Price = 49.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 2,
                            Size = 46
                        },
                        new
                        {
                            Id = 11,
                            Description = "High-quality Puma shoe, model HyperRush, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma HyperRush",
                            Price = 54.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 3,
                            Size = 36
                        },
                        new
                        {
                            Id = 12,
                            Description = "High-quality Puma shoe, model AeroStride, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma AeroStride",
                            Price = 59.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 1,
                            Size = 37
                        },
                        new
                        {
                            Id = 13,
                            Description = "High-quality Puma shoe, model Thunder Run, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma Thunder Run",
                            Price = 64.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 38
                        },
                        new
                        {
                            Id = 14,
                            Description = "High-quality Puma shoe, model FloatStep, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma FloatStep",
                            Price = 69.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 3,
                            Size = 39
                        },
                        new
                        {
                            Id = 15,
                            Description = "High-quality New Balance shoe, model ZoomDrive, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance ZoomDrive",
                            Price = 74.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 1,
                            Size = 40
                        },
                        new
                        {
                            Id = 16,
                            Description = "High-quality Reebok shoe, model VaporSwift, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok VaporSwift",
                            Price = 79.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 2,
                            Size = 41
                        },
                        new
                        {
                            Id = 17,
                            Description = "High-quality New Balance shoe, model PulseZoom, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance PulseZoom",
                            Price = 84.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 3,
                            Size = 42
                        },
                        new
                        {
                            Id = 18,
                            Description = "High-quality Nike shoe, model AeroCushion, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike AeroCushion",
                            Price = 89.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 1,
                            Size = 43
                        },
                        new
                        {
                            Id = 19,
                            Description = "High-quality Nike shoe, model GripMaster, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike GripMaster",
                            Price = 94.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 2,
                            Size = 44
                        },
                        new
                        {
                            Id = 20,
                            Description = "High-quality Nike shoe, model Stealth Glide, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike Stealth Glide",
                            Price = 49.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 3,
                            Size = 45
                        },
                        new
                        {
                            Id = 21,
                            Description = "High-quality Reebok shoe, model LunarStride, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok LunarStride",
                            Price = 54.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 1,
                            Size = 46
                        },
                        new
                        {
                            Id = 22,
                            Description = "High-quality Puma shoe, model RapidFlex, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma RapidFlex",
                            Price = 59.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 36
                        },
                        new
                        {
                            Id = 23,
                            Description = "High-quality Puma shoe, model Nova Flow, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma Nova Flow",
                            Price = 64.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 3,
                            Size = 37
                        },
                        new
                        {
                            Id = 24,
                            Description = "High-quality Reebok shoe, model JumpX, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok JumpX",
                            Price = 69.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 1,
                            Size = 38
                        },
                        new
                        {
                            Id = 25,
                            Description = "High-quality New Balance shoe, model OmniRun, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance OmniRun",
                            Price = 74.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 2,
                            Size = 39
                        },
                        new
                        {
                            Id = 26,
                            Description = "High-quality Nike shoe, model Phantom Flex, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike Phantom Flex",
                            Price = 79.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 3,
                            Size = 40
                        },
                        new
                        {
                            Id = 27,
                            Description = "High-quality Adidas shoe, model TrailMax, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas TrailMax",
                            Price = 84.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 1,
                            Size = 41
                        },
                        new
                        {
                            Id = 28,
                            Description = "High-quality Reebok shoe, model SonicStep, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok SonicStep",
                            Price = 89.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 2,
                            Size = 42
                        },
                        new
                        {
                            Id = 29,
                            Description = "High-quality New Balance shoe, model CrossCharge, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance CrossCharge",
                            Price = 94.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 3,
                            Size = 43
                        },
                        new
                        {
                            Id = 30,
                            Description = "High-quality Nike shoe, model AeroRun, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike AeroRun",
                            Price = 49.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 1,
                            Size = 44
                        },
                        new
                        {
                            Id = 31,
                            Description = "High-quality Reebok shoe, model IgniteWave, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok IgniteWave",
                            Price = 54.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 2,
                            Size = 45
                        },
                        new
                        {
                            Id = 32,
                            Description = "High-quality Nike shoe, model GlideFuel, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike GlideFuel",
                            Price = 59.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 3,
                            Size = 46
                        },
                        new
                        {
                            Id = 33,
                            Description = "High-quality Adidas shoe, model UltraLight, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas UltraLight",
                            Price = 64.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 1,
                            Size = 36
                        },
                        new
                        {
                            Id = 34,
                            Description = "High-quality Puma shoe, model AirVolt, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma AirVolt",
                            Price = 69.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 2,
                            Size = 37
                        },
                        new
                        {
                            Id = 35,
                            Description = "High-quality Reebok shoe, model TerraBoost, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok TerraBoost",
                            Price = 74.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 3,
                            Size = 38
                        },
                        new
                        {
                            Id = 36,
                            Description = "High-quality New Balance shoe, model CloudRush, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance CloudRush",
                            Price = 79.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 1,
                            Size = 39
                        },
                        new
                        {
                            Id = 37,
                            Description = "High-quality Adidas shoe, model HyperGrip, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas HyperGrip",
                            Price = 84.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 2,
                            Size = 40
                        },
                        new
                        {
                            Id = 38,
                            Description = "High-quality New Balance shoe, model SwiftStrike, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance SwiftStrike",
                            Price = 89.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 3,
                            Size = 41
                        },
                        new
                        {
                            Id = 39,
                            Description = "High-quality Puma shoe, model SpeedStorm, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma SpeedStorm",
                            Price = 94.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 1,
                            Size = 42
                        },
                        new
                        {
                            Id = 40,
                            Description = "High-quality Adidas shoe, model EdgeMax, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas EdgeMax",
                            Price = 49.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 2,
                            Size = 43
                        },
                        new
                        {
                            Id = 41,
                            Description = "High-quality Nike shoe, model AlphaCharge, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike AlphaCharge",
                            Price = 54.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 3,
                            Size = 44
                        },
                        new
                        {
                            Id = 42,
                            Description = "High-quality New Balance shoe, model MaxPropel, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance MaxPropel",
                            Price = 59.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 1,
                            Size = 45
                        },
                        new
                        {
                            Id = 43,
                            Description = "High-quality New Balance shoe, model ZeroGravity, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "New Balance ZeroGravity",
                            Price = 64.99m,
                            ShoeBrandId = 5,
                            ShoeCategoryId = 2,
                            Size = 46
                        },
                        new
                        {
                            Id = 44,
                            Description = "High-quality Reebok shoe, model PowerDash, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok PowerDash",
                            Price = 69.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 3,
                            Size = 36
                        },
                        new
                        {
                            Id = 45,
                            Description = "High-quality Adidas shoe, model AeroSpeed, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Adidas AeroSpeed",
                            Price = 74.99m,
                            ShoeBrandId = 2,
                            ShoeCategoryId = 1,
                            Size = 37
                        },
                        new
                        {
                            Id = 46,
                            Description = "High-quality Reebok shoe, model ZoomJet, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok ZoomJet",
                            Price = 79.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 2,
                            Size = 38
                        },
                        new
                        {
                            Id = 47,
                            Description = "High-quality Puma shoe, model StormRunner, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Puma StormRunner",
                            Price = 84.99m,
                            ShoeBrandId = 3,
                            ShoeCategoryId = 3,
                            Size = 39
                        },
                        new
                        {
                            Id = 48,
                            Description = "High-quality Reebok shoe, model GlideWave, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok GlideWave",
                            Price = 89.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 1,
                            Size = 40
                        },
                        new
                        {
                            Id = 49,
                            Description = "High-quality Nike shoe, model HydroFlow, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Nike HydroFlow",
                            Price = 94.99m,
                            ShoeBrandId = 1,
                            ShoeCategoryId = 2,
                            Size = 41
                        },
                        new
                        {
                            Id = 50,
                            Description = "High-quality Reebok shoe, model PulseStrider, with excellent comfort.",
                            ImageUrl = "https://images.unsplash.com/photo-1605348532760-6753d2c43329?q=80&w=1920&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
                            Name = "Reebok PulseStrider",
                            Price = 49.99m,
                            ShoeBrandId = 4,
                            ShoeCategoryId = 3,
                            Size = 42
                        });
                });

            modelBuilder.Entity("Server.Core.Entities.ShoeBrand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nike"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adidas"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Puma"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Reebok"
                        },
                        new
                        {
                            Id = 5,
                            Name = "New Balance"
                        });
                });

            modelBuilder.Entity("Server.Core.Entities.ShoeCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Shoes for running and jogging",
                            Name = "Running"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Everyday wear shoes",
                            Name = "Casual"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Elegant formal shoes",
                            Name = "Formal"
                        });
                });

            modelBuilder.Entity("Server.Core.Entities.Shoe", b =>
                {
                    b.HasOne("Server.Core.Entities.ShoeBrand", "ShoeBrand")
                        .WithMany("Shoes")
                        .HasForeignKey("ShoeBrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Server.Core.Entities.ShoeCategory", "ShoeCategory")
                        .WithMany("Shoes")
                        .HasForeignKey("ShoeCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ShoeBrand");

                    b.Navigation("ShoeCategory");
                });

            modelBuilder.Entity("Server.Core.Entities.ShoeBrand", b =>
                {
                    b.Navigation("Shoes");
                });

            modelBuilder.Entity("Server.Core.Entities.ShoeCategory", b =>
                {
                    b.Navigation("Shoes");
                });
#pragma warning restore 612, 618
        }
    }
}
